package cl.open.openproject.bean;

//TODO Revisada

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserBean implements java.io.Serializable {

	private Integer userId;
	private Integer customerId;
	private String userName;
	private String userPassword;
	private Integer userStatus;
	private String userMail;

	public UserBean() {
	}

	public UserBean(String userMail) {
		this.userMail = userMail;
	}

	public UserBean(Integer customerId, String userName, String userPassword,
			Integer userStatus, String userMail) {
		this.customerId = customerId;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userStatus = userStatus;
		this.userMail = userMail;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Integer getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

}
