package cl.open.openproject.menu.pojo;

// Generated 22-07-2010 06:35:20 PM by Hibernate Tools 3.3.0.GA

/**
 * Resource generated by hbm2java
 */
@SuppressWarnings("serial")
public class Resource implements java.io.Serializable {

	private Integer ResourceID;
	private String ResourceLabel;
	private String ResourceLinkURL;
	private Integer ResourceParentID;
	private Integer ResourceLoginFlg;
	private Integer ResourceOrderMenu;
	private Integer ResourceStatus;
	private Integer ResourceLevel;

	public Resource() {
	}

	public Resource(Integer ResourceID) {
		this.ResourceID = ResourceID;
	}

	public Resource(Integer ResourceID, String ResourceLabel,
			String ResourceLinkURL, Integer ResourceParentID,
			Integer ResourceLoginFlg, Integer ResourceOrderMenu,
			Integer ResourceStatus, Integer ResourceLevel) {
		this.ResourceID = ResourceID;
		this.ResourceLabel = ResourceLabel;
		this.ResourceLinkURL = ResourceLinkURL;
		this.ResourceParentID = ResourceParentID;
		this.ResourceLoginFlg = ResourceLoginFlg;
		this.ResourceOrderMenu = ResourceOrderMenu;
		this.ResourceStatus = ResourceStatus;
		this.ResourceLevel = ResourceLevel;
	}

	public Integer getResourceID() {
		return this.ResourceID;
	}

	public void setResourceID(Integer ResourceID) {
		this.ResourceID = ResourceID;
	}

	public String getResourceLabel() {
		return this.ResourceLabel;
	}

	public void setResourceLabel(String ResourceLabel) {
		this.ResourceLabel = ResourceLabel;
	}

	public String getResourceLinkURL() {
		return this.ResourceLinkURL;
	}

	public void setResourceLinkURL(String ResourceLinkURL) {
		this.ResourceLinkURL = ResourceLinkURL;
	}

	public Integer getResourceParentID() {
		return this.ResourceParentID;
	}

	public void setResourceParentID(Integer ResourceParentID) {
		this.ResourceParentID = ResourceParentID;
	}

	public Integer getResourceLoginFlg() {
		return this.ResourceLoginFlg;
	}

	public void setResourceLoginFlg(Integer ResourceLoginFlg) {
		this.ResourceLoginFlg = ResourceLoginFlg;
	}

	public Integer getResourceOrderMenu() {
		return this.ResourceOrderMenu;
	}

	public void setResourceOrderMenu(Integer ResourceOrderMenu) {
		this.ResourceOrderMenu = ResourceOrderMenu;
	}

	public Integer getResourceStatus() {
		return this.ResourceStatus;
	}

	public void setResourceStatus(Integer ResourceStatus) {
		this.ResourceStatus = ResourceStatus;
	}

	public Integer getResourceLevel() {
		return this.ResourceLevel;
	}

	public void setResourceLevel(Integer ResourceLevel) {
		this.ResourceLevel = ResourceLevel;
	}

}
