package cl.open.openproject.menu.pojo;

// Generated 22-07-2010 06:35:20 PM by Hibernate Tools 3.3.0.GA

/**
 * Resource_has_rol generated by hbm2java
 */
@SuppressWarnings("serial")
public class Resource_has_rol implements java.io.Serializable {

	private Integer RolID;
	private Integer ResourceID;

	public Resource_has_rol() {
	}

	public Resource_has_rol(Integer RolID) {
		this.RolID = RolID;
	}

	public Resource_has_rol(Integer RolID, Integer ResourceID) {
		this.RolID = RolID;
		this.ResourceID = ResourceID;
	}


	public Integer getRolID() {
		return this.RolID;
	}

	public void setRolID(Integer RolID) {
		this.RolID = RolID;
	}

	public Integer getResourceID() {
		return this.ResourceID;
	}

	public void setResourceID(Integer ResourceID) {
		this.ResourceID = ResourceID;
	}

}
