package cl.open.openproject.pojo;

// Generated 22-07-2010 06:35:20 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**malo 
 * Rol generated by hbm2java
 */
@SuppressWarnings("serial")
public class Rol implements java.io.Serializable {

	private Integer RolID;
	private String RolLabel;
	private String RolDescription;
	private Date RolCrDate;
	private Integer RolStatus;

	public Rol() {
	}

	public Rol(Integer RolID) {
		this.RolID = RolID;
	}

	public Rol(Integer RolID, String RolLabel, String RolDescription,
			Date RolCrDate, Integer RolStatus) {
		this.RolID = RolID;
		this.RolLabel = RolLabel;
		this.RolDescription = RolDescription;
		this.RolCrDate = RolCrDate;
		this.RolStatus = RolStatus;
	}

	public Integer getRolID() {
		return this.RolID;
	}

	public void setRolID(Integer RolID) {
		this.RolID = RolID;
	}

	public String getRolLabel() {
		return this.RolLabel;
	}

	public void setRolLabel(String RolLabel) {
		this.RolLabel = RolLabel;
	}

	public String getRolDescription() {
		return this.RolDescription;
	}

	public void setRolDescription(String RolDescription) {
		this.RolDescription = RolDescription;
	}

	public Date getRolCrDate() {
		return this.RolCrDate;
	}

	public void setRolCrDate(Date RolCrDate) {
		this.RolCrDate = RolCrDate;
	}

	public Integer getRolStatus() {
		return this.RolStatus;
	}

	public void setRolStatus(Integer RolStatus) {
		this.RolStatus = RolStatus;
	}

}
