package cl.open.openproject.pojo;

// Generated 22-07-2010 06:35:20 PM by Hibernate Tools 3.3.0.GA

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	private Integer UserID;
	private Integer CustomerID;
	private String UserName;
	private String UserPassword;
	private String UserStatus;

	public User() {
	}

	public User(Integer UserID) {
		this.UserID = UserID;
	}

	public User(Integer UserID, Integer CustomerID, String UserName,
			String UserPassword, String UserStatus) {
		this.UserID = UserID;
		this.CustomerID = CustomerID;
		this.UserName = UserName;
		this.UserPassword = UserPassword;
		this.UserStatus = UserStatus;
	}

	public Integer getUserID() {
		return this.UserID;
	}

	public void setUserID(Integer UserID) {
		this.UserID = UserID;
	}

	public Integer getCustomerID() {
		return this.CustomerID;
	}

	public void setCustomerID(Integer CustomerID) {
		this.CustomerID = CustomerID;
	}

	public String getUserName() {
		return this.UserName;
	}

	public void setUserName(String UserName) {
		this.UserName = UserName;
	}

	public String getUserPassword() {
		return this.UserPassword;
	}

	public void setUserPassword(String UserPassword) {
		this.UserPassword = UserPassword;
	}

	public String getUserStatus() {
		return this.UserStatus;
	}

	public void setUserStatus(String UserStatus) {
		this.UserStatus = UserStatus;
	}

}
