package cl.open.openproject.pojo;

// Generated 22-07-2010 06:35:20 PM by Hibernate Tools 3.3.0.GA

/**
 * User_has_rol generated by hbm2java
 */
@SuppressWarnings("serial")
public class User_has_rol implements java.io.Serializable {

	private Integer RolID;
	private Integer UserID;

	public User_has_rol() {
	}

	public User_has_rol(Integer RolID) {
		this.RolID = RolID;
	}

	public User_has_rol(Integer RolID, Integer UserID) {
		this.RolID = RolID;
		this.UserID = UserID;
	}

	public Integer getRolID() {
		return this.RolID;
	}

	public void setRolID(Integer RolID) {
		this.RolID = RolID;
	}

	public Integer getUserID() {
		return this.UserID;
	}

	public void setUserID(Integer UserID) {
		this.UserID = UserID;
	}

}
